### PR TITLE
Swift 5.5 Concurrency Extension

### PR DESCRIPTION
**Pull request by richardpiazza**
Adds basic support for Swift 5.5 Concurrency by supplying `async` implementations of the `Flagsmith` functions.

Each of these use the new `withCheckedThrowingContinuation()` method in Swift to wrap the existing synchronous completion-handler based methods. The entire extension is wrapped in a compiler check for a Swift environment of 5.5 or greater.

### CODE REVIEW

**Comment by dabeeeenster** [comment]
Thanks for this! Are you able to add some documentation around how you would implement this?

**Comment by richardpiazza** [comment]
@dabeeeenster Sure thing... do you have a specific place in mind that documentation should go?
* Something in the readme
* File header comments
* Adding to the example project

**Comment by dabeeeenster** [comment]
Here https://github.com/Flagsmith/flagsmith-docs/blob/main/docs/clients/client-side/ios.md
and an example in this repo would be great - thanks!

**Comment by richardpiazza** [comment]
I've update the Example project and included a sample usage of the `async` methods. Additionally, new documentation has been added [here](https://github.com/Flagsmith/flagsmith-docs/pull/59).

**Comment by dabeeeenster** [comment]
Awesome thank you so much!

**Pull request merged**
